version: "3.9"

services:
  e2e_wishlist_postgres:
    container_name: e2e_wishlist_postgres
    hostname: e2e_wishlist_postgres
    restart: always
    image: postgres:15.3
    environment:
      POSTGRES_MULTIPLE_DATABASES: e2e_wishlist, test_e2e_wishlist
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - e2e_wishlist_data:/var/lib/postgresql/data
      - ./db_scripts/pg_many_db:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - 7001:5432
    networks:
      - e2e_wishlist

volumes:
  e2e_wishlist_data:

networks:
  e2e_wishlist:
    name: e2e_wishlist
    driver: bridge
